image: microsoft/dotnet:2.1-sdk-alpine

pipelines:
  default:
    - step:
        name: test
        script:
          - "sh ./runTest.sh"
        services: 
          - db  
        artifacts: 
          - "**/coverage-results/**" # use coverage files next step.
          - "**/test-reports/**"
    - step:
        name: publish report to bitbucket download
        # see https://confluence.atlassian.com/bitbucket/deploy-build-artifacts-to-bitbucket-downloads-872124574.html
        image: eamonwoortman/alpine-curl-zip
        script:
          - "zip -r coverage_${BITBUCKET_BRANCH}_${BITBUCKET_BUILD_NUMBER}.zip coverage-results"
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"coverage_${BITBUCKET_BRANCH}_${BITBUCKET_BUILD_NUMBER}.zip"
          - "zip -r ut_${BITBUCKET_BRANCH}_${BITBUCKET_BUILD_NUMBER}.zip test-results"
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"ut_${BITBUCKET_BRANCH}_${BITBUCKET_BUILD_NUMBER}.zip"

definitions:
  services:
    db:
      image: microsoft/mssql-server-linux:2017-CU8
      memory: 2048 #notice! mssql need minimum 2G RAM 
      environment: 
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: 'SqlServerPass01' 
