image: microsoft/dotnet:2.1-sdk-alpine

pipelines:
  default:
    - step:
        name: test
        script:
          - "sleep 20"
          - "sh ./runTest.sh"
        services: 
          - db  
        artifacts: 
          - "coverage-results/**" # use coverage files next step.
          - "test-results/**"
    - step:
        name: publish report to codecov
        script:
          - bash <(curl -s https://codecov.io/bash)
definitions:
  services:
    db:
      image: microsoft/mssql-server-linux:2017-CU8
      memory: 2048 #notice! mssql need minimum 2G RAM 
      environment: 
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: 'SqlServerPass01' 
